### PR TITLE
Switch default sort type to descending

### PR DESCRIPTION
**Pull request by mdevine82**
Minor change referenced in issue #6 to just change the default sort to descending.

### CODE REVIEW

**Comment by mdevine82** [comment]
Github was having problem when this was updated.  I doubt it would fail, but I don't know how to redo the tests

**Comment by staabm** [comment]
Restarted the build...

**Comment by mdevine82** [comment]
Doesn't appear like it was ever restarted

**Comment by staabm** [comment]
Restarted again :)

**Comment by mdevine82** [comment]
Any idea as to why its being unsuccessful?

**Comment by staabm** [comment]
travis seems to have some issues... I merged this nevertheless. thank you

**Pull request merged**
